server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vocab_db
    username: vinhnguyen
    password: quangvinh263
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: NHE4cTZ0OHcyZTRmN2g5ajJrMW0zbjVxOHM3djZ4NXo=
  expiration: 86400000